services:
  - type: web
    name: mjdownloader
    env: node
    plan: free
    buildCommand: curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o yt-dlp && chmod +x yt-dlp
    startCommand: node server.js
